// Auto-generated by hub-codegen
// Do not edit manually

/** Echo response */
export interface EchoEventEcho {
  type: 'echo';
  /** Number of times repeated */
  count: number;
  /** The echoed message */
  message: string;
}

/** Events from echo operations */
export type EchoEvent = EchoEventEcho;

export function isEchoEventEcho(e: EchoEvent): e is EchoEventEcho { return e.type === 'echo'; }
